# Generated by Django 5.2.6 on 2025-09-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('jersey', 'Jersey'), ('ball', 'Ball'), ('merchandise', 'Merchandise'), ('accessories', 'Accessories'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
